---
title: "R Notebook"
output: html_notebook
---
```{r}
library(googlesheets)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```
```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF 
```
```{r}
names(StuDF)
```

```{r}
names(StuDF)[2] <- c("姓名")  ##只改一個column name
names(StuDF)
```


```{r}
names(StuDF) <- c("學號","姓名","成績")
names(StuDF)
```
```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student$身高級距)
```

```{r}
levels(student$身高級距)[1:3] <- "(0,160]" 
```
```{r}
levels(student$身高級距)[1:5] <- "小個子"
levels(student$身高級距)[2:3] <- "中等個子"
levels(student$身高級距)[3:4] <- "高個子"
```
```{r}
library(stringr)
as.character(classSurvey$學號)
classSurvey$年級 <- str_sub(classSurvey$學號,2,4)
table(classSurvey$年級)
as.factor(classSurvey$年級)
classSurvey  %<>% mutate(
  年級=cut(學號,c("104","105","106","107")))
levels(classSurvey$年級)
```

