---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
collegeData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6231&md5_url=dda8fca407131483c1d8cbf3d61cf793")
```

```{r}
mutate(
  collegeData,
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱)
  ) -> collegeData2
```

```{r}
# 不用mutate
collegeData3 <- collegeData
collegeData$學校代碼 <- as.factor(collegeData3$學校代碼)
collegeData$學校名稱 <- as.factor(collegeData3$學校名稱)
```

```{r}
mutate(
  collegeData,
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱),
  `日間∕進修別`=as.factor(`日間∕進修別`),
  一年級男生=as.numeric(一年級男生),
  一年級女生=as.numeric(一年級女生)
  ) -> collegeData4
```

```{r}
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=as.numeric(一年級男生),
    一年級女生=as.numeric(一年級女生)
  ) -> collegeData5
```

```{r}
library(readr)
cl<-locale(grouping_mark = ",") # 創造cl來描述千分位符號使用","的習慣場景
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=parse_number(一年級男生,locale=cl),
    一年級女生=parse_number(一年級女生,locale=cl)
  ) -> collegeData6
```

```{r}
problems(collegeData6$一年級男生)
```

